### ISSUE TITLE
Roles or Links

### ISSUE THREAD

**Issue by strich3** [bycop/Discord-global-chat#1]
Please make roles or block links! (Spam too)

**Comment by bycop** [comment]
Restrict command for a type of user ? 
And block all links ?

**Comment by bycop** [comment]
> Please make roles or block links! (Spam too)

Up

**Comment by strich3** [comment]
yey thanks :)

**Comment by ClaraCrazy** [comment]
blocking links would be easy. showing roles could be nice but blocking roles is just a matter of prohibiting a role from seeing the channel so I dont see why we would have to code that.

**Comment by ClaraCrazy** [comment]
(yes @bycop im just considering myself a dev for the two repos lol)

**Comment by bycop** [comment]
> (yes @bycop im just considering myself a dev for the two repos lol)

Aahahahah

**Comment by strich3** [comment]
complete rewrite ok haha

**Comment by ClaraCrazy** [comment]
ye bc im cool
