### ISSUE TITLE
Use webhooks instead of embeds

### ISSUE THREAD

**Issue by ClaraCrazy** [bycop/Discord-global-chat#2]
With webhooks you can clone the user avatar and name and make it look more like a "real chat"

**Comment by bycop** [comment]
Good idea i'll take care of that when i'm available

**Comment by ClaraCrazy** [comment]
any idea when you have some time to work on this?

**Comment by bycop** [comment]
I'll check this night

**Comment by ClaraCrazy** [comment]
Despite me saying "use webhooks" im currently working on a overhaul of the embed version (and actually like it haha)
i might open a pull-request later

**Comment by ClaraCrazy** [comment]
Check PR´s - Closed
