### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by strich3** [bycop/Discord-global-chat#8]
setglobal command, idk why but its kinda cool xd

**Comment by strich3** [comment]
whoups already exists haha

**Comment by ClaraCrazy** [comment]
can you stop opening issues and instantly closing them?

u can unban... just read the notes.
and why use setglobal if you can just go into the file? this would require making a seperate config file which I currently dont have the time to. In fact I dont have the time to work on this painfully ugly code at all

**Comment by strich3** [comment]
> can you stop opening issues and instantly closing them?
> 
> u can unban... just read the notes.
> and why use setglobal if you can just go into the file? this would require making a seperate config file which I currently dont have the time to. In fact I dont have the time to work on this painfully ugly code at all

Sorry
